### ISSUE TITLE
[docs] Switching theme

### ISSUE THREAD

**Issue by iamale** [SunDwarf/Kyoukai#16]
How about switching theme to something more neat and tidy looking? I think http://docs.graphene-python.org/en/latest/ has the Material-ish feel you're trying to achieve while setting aside the navigation and not getting in the way with these permalink icons in headings ::

![screen shot 2016-11-13 at 03 06 11](https://cloud.githubusercontent.com/assets/1298948/20242842/8c10760a-a956-11e6-8f48-8642c4715a9b.png)

I think it could be a good starting point. If you like it too, I can adopt it from [their website's repo](https://github.com/graphql-python/graphene-python.org/tree/docs) to a standalone theme.

**Comment by SunDwarf** [comment]
Sorry about ignoring this issue for so long - I've been simultaneously avoiding and working on the 2.0 rewrite which changes a lot.

Looking at this theme, it definitely looks great and is better than the other material design theme I found (the one that is currently in usage). I was planning to (with my limited design skills available) perform some CSS tweaks to the current theme so that it would look better, but looking at this shows it seems much better

Assuming it's all licenced properly and compatible, I would very much appreciate it if this new theme was ported over to the current/new documentation.

**Comment by iamale** [comment]
So okay, I've basically started porting it (just today, yeah) but it's still far from perfect. Here's [how it looks now](https://sphinx-kanata-preview.surge.sh/).

**Comment by SunDwarf** [comment]
Damn, that looks good!
